// Mocks generated by Mockito 5.4.6 from annotations
// in tafsiri/test/translator/mock_ai_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:tafsiri/core/services/ai_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiService extends _i1.Mock implements _i2.AiService {
  MockAiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> translate({
    required String? text,
    required String? targetLanguage,
    required String? altLanguage,
    required String? apiKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#translate, [], {
              #text: text,
              #targetLanguage: targetLanguage,
              #altLanguage: altLanguage,
              #apiKey: apiKey,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#translate, [], {
                  #text: text,
                  #targetLanguage: targetLanguage,
                  #altLanguage: altLanguage,
                  #apiKey: apiKey,
                }),
              ),
            ),
          )
          as _i3.Future<String>);
}
